sudo: required
dist: trusty
language: ruby
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends ghc cabal-install
  - sudo cabal update
  - git clone https://github.com/koalaman/shellcheck.git
  - cd shellcheck
  - sudo cabal install
before_script:
  - export PATH="$HOME/.cabal/bin/:$PATH"
rvm:
- 2.0.0
- 2.1
- 2.2
- 2.3.1
